[
  {
    name: "Iceland",
    region: "Europe",
    population: 366425,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/is.svg",
  },
  {
    name: "Kingdom of Spain",
    region: "Europe",
    population: 47351567,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/es.svg",
  },
  {
    name: "Republic of Iraq",
    region: "Asia",
    population: 40222503,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/iq.svg",
  },
  {
    name: "Republic of Malawi",
    region: "Africa",
    population: 19129955,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/mw.svg",
  },
  {
    name: "Hong Kong Special Administrative Region of the People's Republic of China",
    region: "Asia",
    population: 7500700,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/hk.svg",
  },
  {
    name: "Republic of Malta",
    region: "Europe",
    population: 525285,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/mt.svg",
  },
  {
    name: "Republic of Paraguay",
    region: "Americas",
    population: 7132530,
    continent: "South America",
    flagUrl: "https://flagcdn.com/py.svg",
  },
  {
    name: "Republic of Djibouti",
    region: "Africa",
    population: 988002,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/dj.svg",
  },
  {
    name: "Republic of Madagascar",
    region: "Africa",
    population: 27691019,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/mg.svg",
  },
  {
    name: "Federal Democratic Republic of Nepal",
    region: "Asia",
    population: 29136808,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/np.svg",
  },
  {
    name: "Republic of San Marino",
    region: "Europe",
    population: 33938,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/sm.svg",
  },
  {
    name: "Kingdom of the Netherlands",
    region: "Europe",
    population: 16655799,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/nl.svg",
  },
  {
    name: "Greenland",
    region: "Americas",
    population: 56367,
    continent: "North America",
    flagUrl: "https://flagcdn.com/gl.svg",
  },
  {
    name: "Kingdom of Norway",
    region: "Europe",
    population: 5379475,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/no.svg",
  },
  {
    name: "Tuvalu",
    region: "Oceania",
    population: 11792,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/tv.svg",
  },
  {
    name: "Lebanese Republic",
    region: "Asia",
    population: 6825442,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/lb.svg",
  },
  {
    name: "Burkina Faso",
    region: "Africa",
    population: 20903278,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/bf.svg",
  },
  {
    name: "Republic of Cabo Verde",
    region: "Africa",
    population: 555988,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/cv.svg",
  },
  {
    name: "Gibraltar",
    region: "Europe",
    population: 33691,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/gi.svg",
  },
  {
    name: "People's Democratic Republic of Algeria",
    region: "Africa",
    population: 44700000,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/dz.svg",
  },
  {
    name: "Georgia",
    region: "Asia",
    population: 3714000,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ge.svg",
  },
  {
    name: "Mongolia",
    region: "Asia",
    population: 3278292,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/mn.svg",
  },
  {
    name: "Islamic Republic of Iran",
    region: "Asia",
    population: 83992953,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ir.svg",
  },
  {
    name: "Tokelau",
    region: "Oceania",
    population: 1411,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/tk.svg",
  },
  {
    name: "Republic of Singapore",
    region: "Asia",
    population: 5685807,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/sg.svg",
  },
  {
    name: "Guiana",
    region: "Americas",
    population: 254541,
    continent: "South America",
    flagUrl: "https://flagcdn.com/gf.svg",
  },
  {
    name: "Martinique",
    region: "Americas",
    population: 378243,
    continent: "North America",
    flagUrl: "https://flagcdn.com/mq.svg",
  },
  {
    name: "Virgin Islands",
    region: "Americas",
    population: 30237,
    continent: "North America",
    flagUrl: "https://flagcdn.com/vg.svg",
  },
  {
    name: "Republic of Nicaragua",
    region: "Americas",
    population: 6624554,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ni.svg",
  },
  {
    name: "Republic of Moldova",
    region: "Europe",
    population: 2617820,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/md.svg",
  },
  {
    name: "Republic of Yemen",
    region: "Asia",
    population: 29825968,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ye.svg",
  },
  {
    name: "Republic of the Gambia",
    region: "Africa",
    population: 2416664,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/gm.svg",
  },
  {
    name: "Kyrgyz Republic",
    region: "Asia",
    population: 6591600,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kg.svg",
  },
  {
    name: "Republic of Cuba",
    region: "Americas",
    population: 11326616,
    continent: "North America",
    flagUrl: "https://flagcdn.com/cu.svg",
  },
  {
    name: "State of Eritrea",
    region: "Africa",
    population: 5352000,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/er.svg",
  },
  {
    name: "Svalbard og Jan Mayen",
    region: "Europe",
    population: 2562,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/sj.svg",
  },
  {
    name: "Republic of El Salvador",
    region: "Americas",
    population: 6486201,
    continent: "North America",
    flagUrl: "https://flagcdn.com/sv.svg",
  },
  {
    name: "Democratic Republic of Timor-Leste",
    region: "Asia",
    population: 1318442,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/tl.svg",
  },
  {
    name: "Republic of Korea",
    region: "Asia",
    population: 51780579,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kr.svg",
  },
  {
    name: "Republic of Mali",
    region: "Africa",
    population: 20250834,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ml.svg",
  },
  {
    name: "Turks and Caicos Islands",
    region: "Americas",
    population: 38718,
    continent: "North America",
    flagUrl: "https://flagcdn.com/tc.svg",
  },
  {
    name: "Republic of Ghana",
    region: "Africa",
    population: 31072945,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/gh.svg",
  },
  {
    name: "Arab Republic of Egypt",
    region: "Africa",
    population: 102334403,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/eg.svg",
  },
  {
    name: "Gabonese Republic",
    region: "Africa",
    population: 2225728,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ga.svg",
  },
  {
    name: "Togolese Republic",
    region: "Africa",
    population: 8278737,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/tg.svg",
  },
  {
    name: "Republic of China (Taiwan)",
    region: "Asia",
    population: 23503349,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/tw.svg",
  },
  {
    name: "Cook Islands",
    region: "Oceania",
    population: 18100,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/ck.svg",
  },
  {
    name: "Kingdom of Eswatini",
    region: "Africa",
    population: 1160164,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sz.svg",
  },
  {
    name: "Sultanate of Oman",
    region: "Asia",
    population: 5106622,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/om.svg",
  },
  {
    name: "Central African Republic",
    region: "Africa",
    population: 4829764,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/cf.svg",
  },
  {
    name: "Italian Republic",
    region: "Europe",
    population: 59554023,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/it.svg",
  },
  {
    name: "Oriental Republic of Uruguay",
    region: "Americas",
    population: 3473727,
    continent: "South America",
    flagUrl: "https://flagcdn.com/uy.svg",
  },
  {
    name: "Commonwealth of the Bahamas",
    region: "Americas",
    population: 393248,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bs.svg",
  },
  {
    name: "Federative Republic of Brazil",
    region: "Americas",
    population: 212559409,
    continent: "South America",
    flagUrl: "https://flagcdn.com/br.svg",
  },
  {
    name: "Republic of the Union of Myanmar",
    region: "Asia",
    population: 54409794,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/mm.svg",
  },
  {
    name: "Vatican City State",
    region: "Europe",
    population: 451,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/va.svg",
  },
  {
    name: "Kingdom of Sweden",
    region: "Europe",
    population: 10353442,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/se.svg",
  },
  {
    name: "Socialist Republic of Vietnam",
    region: "Asia",
    population: 97338583,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/vn.svg",
  },
  {
    name: "Republic of Estonia",
    region: "Europe",
    population: 1331057,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ee.svg",
  },
  {
    name: "Republic of Guinea-Bissau",
    region: "Africa",
    population: 1967998,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/gw.svg",
  },
  {
    name: "Aruba",
    region: "Americas",
    population: 106766,
    continent: "North America",
    flagUrl: "https://flagcdn.com/aw.svg",
  },
  {
    name: "State of Palestine",
    region: "Asia",
    population: 4803269,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ps.svg",
  },
  {
    name: "Republic of Peru",
    region: "Americas",
    population: 32971846,
    continent: "South America",
    flagUrl: "https://flagcdn.com/pe.svg",
  },
  {
    name: "Antigua and Barbuda",
    region: "Americas",
    population: 97928,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ag.svg",
  },
  {
    name: "Heard Island and McDonald Islands",
    region: "Antarctic",
    population: 0,
    continent: "Antarctica",
    flagUrl: "https://flagcdn.com/hm.svg",
  },
  {
    name: "Republic of Burundi",
    region: "Africa",
    population: 11890781,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/bi.svg",
  },
  {
    name: "Hashemite Kingdom of Jordan",
    region: "Asia",
    population: 10203140,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/jo.svg",
  },
  {
    name: "Pitcairn Group of Islands",
    region: "Oceania",
    population: 56,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/pn.svg",
  },
  {
    name: "Republic of Guatemala",
    region: "Americas",
    population: 16858333,
    continent: "North America",
    flagUrl: "https://flagcdn.com/gt.svg",
  },
  {
    name: "French Polynesia",
    region: "Oceania",
    population: 280904,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/pf.svg",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    region: "Antarctic",
    population: 30,
    continent: "Antarctica",
    flagUrl: "https://flagcdn.com/gs.svg",
  },
  {
    name: "Lao People's Democratic Republic",
    region: "Asia",
    population: 7275556,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/la.svg",
  },
  {
    name: "Republic of Sierra Leone",
    region: "Africa",
    population: 7976985,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sl.svg",
  },
  {
    name: "Republic of India",
    region: "Asia",
    population: 1380004385,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/in.svg",
  },
  {
    name: "British Indian Ocean Territory",
    region: "Africa",
    population: 3000,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/io.svg",
  },
  {
    name: "Jamaica",
    region: "Americas",
    population: 2961161,
    continent: "North America",
    flagUrl: "https://flagcdn.com/jm.svg",
  },
  {
    name: "Republic of North Macedonia",
    region: "Europe",
    population: 2077132,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/mk.svg",
  },
  {
    name: "Canada",
    region: "Americas",
    population: 38005238,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ca.svg",
  },
  {
    name: "Guam",
    region: "Oceania",
    population: 168783,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/gu.svg",
  },
  {
    name: "Territory of Norfolk Island",
    region: "Oceania",
    population: 2302,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/nf.svg",
  },
  {
    name: "Federation of Saint Christopher and Nevis",
    region: "Americas",
    population: 53192,
    continent: "North America",
    flagUrl: "https://flagcdn.com/kn.svg",
  },
  {
    name: "Grenada",
    region: "Americas",
    population: 112519,
    continent: "North America",
    flagUrl: "https://flagcdn.com/gd.svg",
  },
  {
    name: "Republic of Liberia",
    region: "Africa",
    population: 5057677,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/lr.svg",
  },
  {
    name: "United States of America",
    region: "Americas",
    population: 329484123,
    continent: "North America",
    flagUrl: "https://flagcdn.com/us.svg",
  },
  {
    name: "Kingdom of Bahrain",
    region: "Asia",
    population: 1701583,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/bh.svg",
  },
  {
    name: "Federal Republic of Germany",
    region: "Europe",
    population: 83240525,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/de.svg",
  },
  {
    name: "Bermuda",
    region: "Americas",
    population: 63903,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bm.svg",
  },
  {
    name: "Malaysia",
    region: "Asia",
    population: 32365998,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/my.svg",
  },
  {
    name: "Independent and Sovereign Republic of Kiribati",
    region: "Oceania",
    population: 119446,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/ki.svg",
  },
  {
    name: "Ukraine",
    region: "Europe",
    population: 44134693,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ua.svg",
  },
  {
    name: "Faroe Islands",
    region: "Europe",
    population: 48865,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/fo.svg",
  },
  {
    name: "Islamic Republic of Afghanistan",
    region: "Asia",
    population: 40218234,
    continent: "Asia",
    flagUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
  },
  {
    name: "Democratic Republic of São Tomé and Príncipe",
    region: "Africa",
    population: 219161,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/st.svg",
  },
  {
    name: "State of Kuwait",
    region: "Asia",
    population: 4270563,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kw.svg",
  },
  {
    name: "Republic of Poland",
    region: "Europe",
    population: 37950802,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/pl.svg",
  },
  {
    name: "Republic of Vanuatu",
    region: "Oceania",
    population: 307150,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/vu.svg",
  },
  {
    name: "Union of the Comoros",
    region: "Africa",
    population: 869595,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/km.svg",
  },
  {
    name: "American Samoa",
    region: "Oceania",
    population: 55197,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/as.svg",
  },
  {
    name: "Niue",
    region: "Oceania",
    population: 1470,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/nu.svg",
  },
  {
    name: "People's Republic of China",
    region: "Asia",
    population: 1402112000,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/cn.svg",
  },
  {
    name: "Sahrawi Arab Democratic Republic",
    region: "Africa",
    population: 510713,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/eh.svg",
  },
  {
    name: "Republic of Panama",
    region: "Americas",
    population: 4314768,
    continent: "North America",
    flagUrl: "https://flagcdn.com/pa.svg",
  },
  {
    name: "Solomon Islands",
    region: "Oceania",
    population: 686878,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/sb.svg",
  },
  {
    name: "Republic of Costa Rica",
    region: "Americas",
    population: 5094114,
    continent: "North America",
    flagUrl: "https://flagcdn.com/cr.svg",
  },
  {
    name: "Independent State of Papua New Guinea",
    region: "Oceania",
    population: 8947027,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/pg.svg",
  },
  {
    name: "Japan",
    region: "Asia",
    population: 125836021,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/jp.svg",
  },
  {
    name: "Republic of South Sudan",
    region: "Africa",
    population: 11193729,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ss.svg",
  },
  {
    name: "Republic of the Marshall Islands",
    region: "Oceania",
    population: 59194,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/mh.svg",
  },
  {
    name: "Principality of Monaco",
    region: "Europe",
    population: 39244,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/mc.svg",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    region: "Africa",
    population: 53192,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sh.svg",
  },
  {
    name: "Sint Maarten",
    region: "Americas",
    population: 40812,
    continent: "North America",
    flagUrl: "https://flagcdn.com/sx.svg",
  },
  {
    name: "Bolivarian Republic of Venezuela",
    region: "Americas",
    population: 28435943,
    continent: "South America",
    flagUrl: "https://flagcdn.com/ve.svg",
  },
  {
    name: "Federated States of Micronesia",
    region: "Oceania",
    population: 115021,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/fm.svg",
  },
  {
    name: "Montserrat",
    region: "Americas",
    population: 4922,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ms.svg",
  },
  {
    name: "Kingdom of Thailand",
    region: "Asia",
    population: 69799978,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/th.svg",
  },
  {
    name: "Bouvet Island",
    region: "Antarctic",
    population: 0,
    continent: "Antarctica",
    flagUrl: "https://flagcdn.com/bv.svg",
  },
  {
    name: "Anguilla",
    region: "Americas",
    population: 13452,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ai.svg",
  },
  {
    name: "Republic of the Philippines",
    region: "Asia",
    population: 109581085,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ph.svg",
  },
  {
    name: "New Zealand",
    region: "Oceania",
    population: 5084300,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/nz.svg",
  },
  {
    name: "Collectivity of Saint Barthélemy",
    region: "Americas",
    population: 4255,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bl.svg",
  },
  {
    name: "Nation of Brunei, Abode of Peace",
    region: "Asia",
    population: 437483,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/bn.svg",
  },
  {
    name: "Slovak Republic",
    region: "Europe",
    population: 5458827,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/sk.svg",
  },
  {
    name: "Republic of the Congo",
    region: "Africa",
    population: 5657000,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/cg.svg",
  },
  {
    name: "Territory of the Wallis and Futuna Islands",
    region: "Oceania",
    population: 11750,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/wf.svg",
  },
  {
    name: "New Caledonia",
    region: "Oceania",
    population: 271960,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/nc.svg",
  },
  {
    name: "Montenegro",
    region: "Europe",
    population: 621718,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/me.svg",
  },
  {
    name: "Territory of the French Southern and Antarctic Lands",
    region: "Antarctic",
    population: 400,
    continent: "Antarctica",
    flagUrl: "https://flagcdn.com/tf.svg",
  },
  {
    name: "Republic of Finland",
    region: "Europe",
    population: 5530719,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/fi.svg",
  },
  {
    name: "Principality of Liechtenstein",
    region: "Europe",
    population: 38137,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/li.svg",
  },
  {
    name: "Republic of Colombia",
    region: "Americas",
    population: 50882884,
    continent: "South America",
    flagUrl: "https://flagcdn.com/co.svg",
  },
  {
    name: "Principality of Andorra",
    region: "Europe",
    population: 77265,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ad.svg",
  },
  {
    name: "Belize",
    region: "Americas",
    population: 397621,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bz.svg",
  },
  {
    name: "Plurinational State of Bolivia",
    region: "Americas",
    population: 11673029,
    continent: "South America",
    flagUrl: "https://flagcdn.com/bo.svg",
  },
  {
    name: "Republic of Niger",
    region: "Africa",
    population: 24206636,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ne.svg",
  },
  {
    name: "Russian Federation",
    region: "Europe",
    population: 144104080,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ru.svg",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    region: "Americas",
    population: 25987,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bq.svg",
  },
  {
    name: "United Republic of Tanzania",
    region: "Africa",
    population: 59734213,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/tz.svg",
  },
  {
    name: "Republic of Zimbabwe",
    region: "Africa",
    population: 14862927,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/zw.svg",
  },
  {
    name: "Antarctica",
    region: "Antarctic",
    population: 1000,
    continent: "Antarctica",
    flagUrl: "https://flagcdn.com/aq.svg",
  },
  {
    name: "Republic of Azerbaijan",
    region: "Asia",
    population: 10110116,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/az.svg",
  },
  {
    name: "Republic of Mauritius",
    region: "Africa",
    population: 1265740,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/mu.svg",
  },
  {
    name: "Republic of Armenia",
    region: "Asia",
    population: 2963234,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/am.svg",
  },
  {
    name: "Czech Republic",
    region: "Europe",
    population: 10698896,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/cz.svg",
  },
  {
    name: "Republic of Haiti",
    region: "Americas",
    population: 11402533,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ht.svg",
  },
  {
    name: "Democratic Socialist Republic of Sri Lanka",
    region: "Asia",
    population: 21919000,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/lk.svg",
  },
  {
    name: "Republic of Albania",
    region: "Europe",
    population: 2837743,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/al.svg",
  },
  {
    name: "Kingdom of Morocco",
    region: "Africa",
    population: 36910558,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ma.svg",
  },
  {
    name: "Virgin Islands of the United States",
    region: "Americas",
    population: 106290,
    continent: "North America",
    flagUrl: "https://flagcdn.com/vi.svg",
  },
  {
    name: "Syrian Arab Republic",
    region: "Asia",
    population: 17500657,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/sy.svg",
  },
  {
    name: "Kingdom of Bhutan",
    region: "Asia",
    population: 771612,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/bt.svg",
  },
  {
    name: "Bailiwick of Jersey",
    region: "Europe",
    population: 100800,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/je.svg",
  },
  {
    name: "Republic of Senegal",
    region: "Africa",
    population: 16743930,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sn.svg",
  },
  {
    name: "Réunion Island",
    region: "Africa",
    population: 840974,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/re.svg",
  },
  {
    name: "Tunisian Republic",
    region: "Africa",
    population: 11818618,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/tn.svg",
  },
  {
    name: "Swiss Confederation",
    region: "Europe",
    population: 8654622,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ch.svg",
  },
  {
    name: "Saint Pierre and Miquelon",
    region: "Americas",
    population: 6069,
    continent: "North America",
    flagUrl: "https://flagcdn.com/pm.svg",
  },
  {
    name: "Grand Duchy of Luxembourg",
    region: "Europe",
    population: 632275,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/lu.svg",
  },
  {
    name: "Independent State of Samoa",
    region: "Oceania",
    population: 198410,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/ws.svg",
  },
  {
    name: "Republic of Austria",
    region: "Europe",
    population: 8917205,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/at.svg",
  },
  {
    name: "Republic of Turkey",
    region: "Asia",
    population: 84339067,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/tr.svg",
  },
  {
    name: "Republic of Latvia",
    region: "Europe",
    population: 1901548,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/lv.svg",
  },
  {
    name: "United Arab Emirates",
    region: "Asia",
    population: 9890400,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/ae.svg",
  },
  {
    name: "Bosnia and Herzegovina",
    region: "Europe",
    population: 3280815,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ba.svg",
  },
  {
    name: "Republic of Botswana",
    region: "Africa",
    population: 2351625,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/bw.svg",
  },
  {
    name: "Bailiwick of Guernsey",
    region: "Europe",
    population: 62999,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/gg.svg",
  },
  {
    name: "Republic of Seychelles",
    region: "Africa",
    population: 98462,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sc.svg",
  },
  {
    name: "Republic of Angola",
    region: "Africa",
    population: 32866268,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ao.svg",
  },
  {
    name: "Commonwealth of Australia",
    region: "Oceania",
    population: 25687041,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/au.svg",
  },
  {
    name: "State of Qatar",
    region: "Asia",
    population: 2881060,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/qa.svg",
  },
  {
    name: "Republic of Slovenia",
    region: "Europe",
    population: 2100126,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/si.svg",
  },
  {
    name: "Republic of Namibia",
    region: "Africa",
    population: 2540916,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/na.svg",
  },
  {
    name: "Saint Martin",
    region: "Americas",
    population: 38659,
    continent: "North America",
    flagUrl: "https://flagcdn.com/mf.svg",
  },
  {
    name: "Republic of Equatorial Guinea",
    region: "Africa",
    population: 1402985,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/gq.svg",
  },
  {
    name: "Territory of Christmas Island",
    region: "Oceania",
    population: 2072,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/cx.svg",
  },
  {
    name: "Kingdom of Cambodia",
    region: "Asia",
    population: 16718971,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kh.svg",
  },
  {
    name: "Republic of Guinea",
    region: "Africa",
    population: 13132792,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/gn.svg",
  },
  {
    name: "Commonwealth of Dominica",
    region: "Americas",
    population: 71991,
    continent: "North America",
    flagUrl: "https://flagcdn.com/dm.svg",
  },
  {
    name: "Republic of Cyprus",
    region: "Europe",
    population: 1207361,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/cy.svg",
  },
  {
    name: "State of Israel",
    region: "Asia",
    population: 9216900,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/il.svg",
  },
  {
    name: "Republic of Côte d'Ivoire",
    region: "Africa",
    population: 26378275,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ci.svg",
  },
  {
    name: "Republic of Uzbekistan",
    region: "Asia",
    population: 34232050,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/uz.svg",
  },
  {
    name: "Republic of Zambia",
    region: "Africa",
    population: 18383956,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/zm.svg",
  },
  {
    name: "Federal Republic of Somalia",
    region: "Africa",
    population: 15893219,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/so.svg",
  },
  {
    name: "Republic of Bulgaria",
    region: "Europe",
    population: 6927288,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/bg.svg",
  },
  {
    name: "Republic of Rwanda",
    region: "Africa",
    population: 12952209,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/rw.svg",
  },
  {
    name: "Kingdom of Belgium",
    region: "Europe",
    population: 11555997,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/be.svg",
  },
  {
    name: "Co-operative Republic of Guyana",
    region: "Americas",
    population: 786559,
    continent: "South America",
    flagUrl: "https://flagcdn.com/gy.svg",
  },
  {
    name: "Republic of Kosovo",
    region: "Europe",
    population: 1775378,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/xk.svg",
  },
  {
    name: "United Mexican States",
    region: "Americas",
    population: 128932753,
    continent: "North America",
    flagUrl: "https://flagcdn.com/mx.svg",
  },
  {
    name: "Kingdom of Denmark",
    region: "Europe",
    population: 5831404,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/dk.svg",
  },
  {
    name: "Democratic Republic of the Congo",
    region: "Africa",
    population: 108407721,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/cd.svg",
  },
  {
    name: "Country of Curaçao",
    region: "Americas",
    population: 155014,
    continent: "North America",
    flagUrl: "https://flagcdn.com/cw.svg",
  },
  {
    name: "Federal Democratic Republic of Ethiopia",
    region: "Africa",
    population: 114963583,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/et.svg",
  },
  {
    name: "Macao Special Administrative Region of the People's Republic of China",
    region: "Asia",
    population: 649342,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/mo.svg",
  },
  {
    name: "Islamic Republic of Pakistan",
    region: "Asia",
    population: 220892331,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/pk.svg",
  },
  {
    name: "Republic of Indonesia",
    region: "Asia",
    population: 273523621,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/id.svg",
  },
  {
    name: "Republic of Nauru",
    region: "Oceania",
    population: 10834,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/nr.svg",
  },
  {
    name: "Commonwealth of the Northern Mariana Islands",
    region: "Oceania",
    population: 57557,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/mp.svg",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    region: "Europe",
    population: 67215293,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/gb.svg",
  },
  {
    name: "Argentine Republic",
    region: "Americas",
    population: 45376763,
    continent: "South America",
    flagUrl: "https://flagcdn.com/ar.svg",
  },
  {
    name: "Republic of Cameroon",
    region: "Africa",
    population: 26545864,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/cm.svg",
  },
  {
    name: "Romania",
    region: "Europe",
    population: 19286123,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ro.svg",
  },
  {
    name: "Republic of Uganda",
    region: "Africa",
    population: 45741000,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ug.svg",
  },
  {
    name: "French Republic",
    region: "Europe",
    population: 67391582,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/fr.svg",
  },
  {
    name: "Republic of Suriname",
    region: "Americas",
    population: 586634,
    continent: "South America",
    flagUrl: "https://flagcdn.com/sr.svg",
  },
  {
    name: "Republic of the Maldives",
    region: "Asia",
    population: 540542,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/mv.svg",
  },
  {
    name: "Republic of Fiji",
    region: "Oceania",
    population: 896444,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/fj.svg",
  },
  {
    name: "Hellenic Republic",
    region: "Europe",
    population: 10715549,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/gr.svg",
  },
  {
    name: "Republic of Trinidad and Tobago",
    region: "Americas",
    population: 1399491,
    continent: "North America",
    flagUrl: "https://flagcdn.com/tt.svg",
  },
  {
    name: "Islamic Republic of Mauritania",
    region: "Africa",
    population: 4649660,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/mr.svg",
  },
  {
    name: "Kingdom of Tonga",
    region: "Oceania",
    population: 105697,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/to.svg",
  },
  {
    name: "Republic of Chile",
    region: "Americas",
    population: 19116209,
    continent: "South America",
    flagUrl: "https://flagcdn.com/cl.svg",
  },
  {
    name: "Republic of Benin",
    region: "Africa",
    population: 12123198,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/bj.svg",
  },
  {
    name: "Republic of the Sudan",
    region: "Africa",
    population: 43849269,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/sd.svg",
  },
  {
    name: "Republic of Chad",
    region: "Africa",
    population: 16425859,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/td.svg",
  },
  {
    name: "Kingdom of Lesotho",
    region: "Africa",
    population: 2142252,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ls.svg",
  },
  {
    name: "Saint Lucia",
    region: "Americas",
    population: 183629,
    continent: "North America",
    flagUrl: "https://flagcdn.com/lc.svg",
  },
  {
    name: "Falkland Islands",
    region: "Americas",
    population: 2563,
    continent: "South America",
    flagUrl: "https://flagcdn.com/fk.svg",
  },
  {
    name: "Republic of Lithuania",
    region: "Europe",
    population: 2794700,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/lt.svg",
  },
  {
    name: "Republic of Mozambique",
    region: "Africa",
    population: 31255435,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/mz.svg",
  },
  {
    name: "Republic of Tajikistan",
    region: "Asia",
    population: 9537642,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/tj.svg",
  },
  {
    name: "Territory of the Cocos (Keeling) Islands",
    region: "Oceania",
    population: 544,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/cc.svg",
  },
  {
    name: "Democratic People's Republic of Korea",
    region: "Asia",
    population: 25778815,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kp.svg",
  },
  {
    name: "Republic of Serbia",
    region: "Europe",
    population: 6908224,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/rs.svg",
  },
  {
    name: "United States Minor Outlying Islands",
    region: "Americas",
    population: 300,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/um.svg",
  },
  {
    name: "Commonwealth of Puerto Rico",
    region: "Americas",
    population: 3194034,
    continent: "North America",
    flagUrl: "https://flagcdn.com/pr.svg",
  },
  {
    name: "Republic of Honduras",
    region: "Americas",
    population: 9904608,
    continent: "North America",
    flagUrl: "https://flagcdn.com/hn.svg",
  },
  {
    name: "Republic of Kenya",
    region: "Africa",
    population: 53771300,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ke.svg",
  },
  {
    name: "Portuguese Republic",
    region: "Europe",
    population: 10305564,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/pt.svg",
  },
  {
    name: "Republic of Belarus",
    region: "Europe",
    population: 9398861,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/by.svg",
  },
  {
    name: "Dominican Republic",
    region: "Americas",
    population: 10847904,
    continent: "North America",
    flagUrl: "https://flagcdn.com/do.svg",
  },
  {
    name: "Department of Mayotte",
    region: "Africa",
    population: 226915,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/yt.svg",
  },
  {
    name: "Republic of Palau",
    region: "Oceania",
    population: 18092,
    continent: "Oceania",
    flagUrl: "https://flagcdn.com/pw.svg",
  },
  {
    name: "Kingdom of Saudi Arabia",
    region: "Asia",
    population: 34813867,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/sa.svg",
  },
  {
    name: "People's Republic of Bangladesh",
    region: "Asia",
    population: 164689383,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/bd.svg",
  },
  {
    name: "Barbados",
    region: "Americas",
    population: 287371,
    continent: "North America",
    flagUrl: "https://flagcdn.com/bb.svg",
  },
  {
    name: "Isle of Man",
    region: "Europe",
    population: 85032,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/im.svg",
  },
  {
    name: "Republic of Kazakhstan",
    region: "Asia",
    population: 18754440,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/kz.svg",
  },
  {
    name: "State of Libya",
    region: "Africa",
    population: 6871287,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ly.svg",
  },
  {
    name: "Cayman Islands",
    region: "Americas",
    population: 65720,
    continent: "North America",
    flagUrl: "https://flagcdn.com/ky.svg",
  },
  {
    name: "Federal Republic of Nigeria",
    region: "Africa",
    population: 206139587,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/ng.svg",
  },
  {
    name: "Republic of Ireland",
    region: "Europe",
    population: 4994724,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ie.svg",
  },
  {
    name: "Republic of South Africa",
    region: "Africa",
    population: 59308690,
    continent: "Africa",
    flagUrl: "https://flagcdn.com/za.svg",
  },
  {
    name: "Republic of Ecuador",
    region: "Americas",
    population: 17643060,
    continent: "South America",
    flagUrl: "https://flagcdn.com/ec.svg",
  },
  {
    name: "Guadeloupe",
    region: "Americas",
    population: 400132,
    continent: "North America",
    flagUrl: "https://flagcdn.com/gp.svg",
  },
  {
    name: "Åland Islands",
    region: "Europe",
    population: 29458,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/ax.svg",
  },
  {
    name: "Saint Vincent and the Grenadines",
    region: "Americas",
    population: 110947,
    continent: "North America",
    flagUrl: "https://flagcdn.com/vc.svg",
  },
  {
    name: "Republic of Croatia",
    region: "Europe",
    population: 4047200,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/hr.svg",
  },
  {
    name: "Hungary",
    region: "Europe",
    population: 9749763,
    continent: "Europe",
    flagUrl: "https://flagcdn.com/hu.svg",
  },
  {
    name: "Turkmenistan",
    region: "Asia",
    population: 6031187,
    continent: "Asia",
    flagUrl: "https://flagcdn.com/tm.svg",
  },
];
